CREATE database sakai default character set utf8;
CREATE user 'sakai_user'@'%.%.%.%' identified by 'Sakai!123';
GRANT ALL PRIVILEGES ON sakai.* TO 'sakai_user'@'%.%.%.%';

CREATE database learna default character set utf8;
CREATE user 'learna_user'@'%.%.%.%' identified by 'LearnA!123';
GRANT ALL PRIVILEGES ON learna.* TO 'learna_user'@'%.%.%.%';

# MySQL Commands to delete database;
REVOKE ALL PRIVILEGES ON learna.* FROM 'learna_user'@'%.%.%.%';
DROP user 'learna_user'@'%.%.%.%';
DROP DATABASE learna;

CREATE database learna default character set utf8;
CREATE user 'learna_user'@'localhost' identified by 'LearnA!123';
GRANT ALL PRIVILEGES ON learna.* TO 'learna_user'@'localhost';

CREATE database learn default character set utf8;
CREATE user 'learn_user'@'localhost' identified by 'Learn!123';
GRANT ALL PRIVILEGES ON learn.* TO 'learn_user'@'localhost';

CREATE user 'learn_user'@'%' identified by 'Learn!123';
GRANT ALL PRIVILEGES ON learn.* TO 'learn_user'@'%';