# For CAS Authentication
loginUrl=https://xmyworkspace.com/cas/login?service\=https://xmyworkspace.com/l4f/j_spring_cas_security_check
logoutUrl=https://xmyworkspace.com/cas/logout?service\=xmyworkspace.com/l4f
theme.root=https://mksol.vn/themes/robust-admin/


driverClassName@javax.sql.BaseDataSource=org.mariadb.jdbc.Driver
url@javax.sql.BaseDataSource=jdbc:mariadb://127.0.0.1:3306/sakai_testing?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
username@javax.sql.BaseDataSource=sakai_testing_user
password@javax.sql.BaseDataSource=Sakai!123
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#url@javax.sql.BaseDataSource=jdbc:mariadb://127.0.0.1:3306/learna?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#username@javax.sql.BaseDataSource=learna_user
#password@javax.sql.BaseDataSource=LearnA!123
#hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

auto.ddl=true
hibernate.show_sql=false
hibernate.hbm2ddl.auto=update
# Payment
payment.sepay.apiKey = ${SEPAY_APIKEY:apiKey}
payment.vnpay.tmnCode=${VNP_TMNCODE:vnpayCode}
payment.vnpay.secretKey=${VNP_SECRETKEY:vnpayKey}