# For CAS Authentication
loginUrl=https://myworkspace.vn/cas/login?service\=http://localhost:8080/codelearna-web/j_spring_cas_security_check
logoutUrl=https://myworkspace.vn/cas/logout?service\=http://localhost:8080/codelearna-web
theme.root=https://mksol.vn/themes/robust-admin/

## Database configuration

#driverClassName@javax.sql.BaseDataSource=org.mariadb.jdbc.Driver
#url@javax.sql.BaseDataSource=jdbc:mariadb://127.0.0.1:3306/learna?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#username@javax.sql.BaseDataSource=learna_user
#password@javax.sql.BaseDataSource=LearnA!123
#hibernate.dialect=org.hibernate.dialect.MariaDBDialect

driverClassName@javax.sql.BaseDataSource=org.mariadb.jdbc.Driver
url@javax.sql.BaseDataSource=jdbc:mariadb://192.168.1.5:3306/learna?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
username@javax.sql.BaseDataSource=learna_user
password@javax.sql.BaseDataSource=LearnA!123
#hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect


auto.ddl=true
hibernate.show_sql=false
hibernate.hbm2ddl.auto=update

# Payment
payment.sepay.apiKey = T5HVZBKPIO1CMOPOIPQ5EGWWUY6A00D83MQWBHBAZQ1KSP4RQKEXRX3OJUCXDW28
payment.sepay.transactionEndpoint = https://my.sepay.vn/userapi/transactions/list?limit=20
payment.sepay.generateQrEndpoint = https://qr.sepay.vn
payment.sepay.accountNumber = 014028268888
payment.sepay.bankCode = MB
payment.sepay.cardholder = VO MINH KHOA
# Payment with Vnpay
payment.vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
payment.vnpay.tmnCode=${VNP_TMNCODE:vnpayCode}
payment.vnpay.secretKey=${VNP_SECRETKEY:vnpayKey}